dist: bionic
language: generic
before_install:
- |
  echo "Checking if a CI run is needed post commit: ${TRAVIS_COMMIT_RANGE}"
  if ! git diff --name-only ${TRAVIS_COMMIT_RANGE} | grep -qvE '(\.png$)|(\.pdf$)|(\.html$)|^(LICENSE)'
  then
    echo "Only doc files were updated, not running the CI."
    exit
  fi
- sudo add-apt-repository --yes ppa:js-reynaud/kicad-5.1
- sudo apt update -y
- sudo apt install --no-install-recommends -y kicad kicad-symbols kicad-templates
  kicad-footprints inkscape
script:
- cd scripts && ./pcb2svg.sh && cd ..
before_deploy:
- git config --local user.name "PCB Gerber Exporter"
- git config --local user.email "noreply@w4xzr.xyz"
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
- git tag $TRAVIS_TAG
- ls
- ls Gerbers/
deploy:
  provider: releases
  api_key:
    secure: WT6Ubw0jJkX6Kp0b9fT8KU0JHFgggGZDAXcPdlZRb4Kji6mtuUJidHIQhAxNdHBAV7Mfrq2U2ky0mr038n17lURefqwn/8mEGTOdNAVlg9r66R6kRr4/F+TAbgoM2hqW9XsI64AWn8+7+yIhaR3l+O98koq2ytsYVIs0/TeSMBa+4Uwduq8T33lJJpthalfM+cCKHS/OnwxENR2yvdA4SFucqgWC8nZ7iInYm0X4gccgBzIQ7V37/8PQDxMfSzp35pF26Bf3Ahz43nE3aOMg61qQoFpF/lb66LDF3eo/1cmIAmtlEpccpmhDjHqq7RaG1FSAFYCTatVMh+HTjGoHaqrVReBrkP+FmeX9zjjtjmYB+4qrz+/UKErLYL1lanoE5BBTDYG60a2qQCZB0u8CAICNGDzH6D2y6P67vzWCOewgjgdMKabPkpbZi5Y9FnYTXjRDfG6PZZYUykFgrpaxA1/YdofBsetj1JwGuRxjT3LGkTFtm7HYooNm3aBMyxM1tb+hqR8UEoLmT+11ih6nFHAfdg4sKocdkUmEQMjMxJtZPId3xtRswmrb8Cu3cwMR4/GPjDJfb46kYRMgwc7jwLIxnn5bu3Nyxa+Zeoryzh/cvNpgwUKhJ235B5FOyD46OHvHu85+hF41cm0khodjiBs6cWF8IZiqDsiKYhTevp8=
  file: Gerbers/MNT-109_gerbers.zip
  on:
    repo: w4xzr/MNT-109
  skip_cleanup: 'true'
